export const progressMessages = [
    "root@user > Initializing Model Parameters...",
    "root@user > Setting up the model’s internal configurations and ensuring optimal resource allocation for story generation.",
    "root@user > Analyzing User Preferences...",
    "root@user > Extracting selected genre, language, story length, and character details to tailor the generated story accordingly.",
    "root@user > Fetching Genre-Specific References...",
    "root@user > Loading narrative structures, themes, and stylistic elements relevant to the selected genre.",
    "root@user > Configuring Language Model...",
    "root@user > Adjusting sentence structures, tone, and vocabulary based on the selected language.",
    "root@user > Building Story Outline...",
    "root@user > Creating a high-level plot structure, including beginning, middle, and end, to guide coherent storytelling.",
    "root@user > Defining Character Archetypes...",
    "root@user > Identifying and constructing protagonist, antagonist, and supporting characters.",
    "root@user > Assigning Character Motivations...",
    "root@user > Generating character backstories, personal motivations, and emotional depth.",
    "root@user > Crafting Major Story Events...",
    "root@user > Outlining key story beats, conflicts, and turning points.",
    "root@user > Establishing Story Logic and Continuity...",
    "root@user > Checking for plot consistency, logical character behavior, and alignment with genre expectations.",
    "root@user > Optimizing Narrative Style...",
    "root@user > Applying stylistic elements, literary techniques, and pacing adjustments.",
    "root@user > Adjusting Word Count and Pacing...",
    "root@user > Scaling narrative content to fit the desired story length.",
    "root@user > Generating Initial Story Draft...",
    "root@user > Constructing a full draft based on all previous steps.",
    "root@user > Enhancing Character Dialogues...",
    "root@user > Ensuring that dialogues reflect character personalities and emotions.",
    "root@user > Smoothing Scene Transitions...",
    "root@user > Refining paragraph flow and event connections.",
    "root@user > Evaluating Story Conflict and Resolution...",
    "root@user > Assessing the stakes, emotional depth, and ensuring the resolution is satisfying.",
    "root@user > Performing Final Edits...",
    "root@user > Checking grammar, punctuation, and stylistic elements for readability.",
    "root@user > Reviewing Final Output...",
    "root@user > Ensuring quality, consistency, and overall coherence before presenting the final story.",
    "root@user > Story Generation Complete!",
    "root@user > The final story is ready and meets all specified parameters."
  ];